## What is NumPy?


In [ ]:
# NumPy is a multi dimensional array library where in you can use it to store 
# in 1D array, 2D array, 3D array etc. 
# How are Lists different from NumPy?
# Lists: Slow
#NumPy: Fast

In [1]:
import numpy as np

## The Basics

In [2]:
#when you make an numpy array always start with np.array and within the 
#parenthesis add a list, it can be a 1D; 2D which has 2 lists in an array
# these two lists are enclosed inside of a list
a = np.array([1,2,3])
print(a)

[1 2 3]


In [67]:
b = np.array([[9.0,8.0,7.0,4.0],[6.0,5.0,4.0,2.0]])
print(b)

[[9. 8. 7. 4.]
 [6. 5. 4. 2.]]


In [13]:
c = np.array([[1.0,2.0],[2.0],[3.0]])
print(c)

[list([1.0, 2.0]) list([2.0]) list([3.0])]


### how to get the dimension of array

In [4]:
a.ndim

1

In [5]:
b.ndim

2

### Get shape

In [6]:
#the shape method gives the number of element in the array
a.shape

(3,)

In [16]:
#here the elements in the array are equal hence it returns a 2x4 which means 
#2 rows and 4 elements : (rows,element) also the no. of elements inside 
#the [] brackets should be same in all the lists.
b.shape

(2, 4)

In [14]:
# here we saw that when we are creating an array the elements with different 
#no. of elements then the array gets converted to a list and it just
#returns the rows in the array and not the elements count
c.shape

(3,)

In [20]:
c.dtype
#here the datatype is object

dtype('O')

In [29]:
#suppose we know that the data in the array is small and we need faster 
#preocessing then we can set the datatype to store as a smaller dtype
a = np.array([1,2,3,4,5],dtype= 'int32')

In [22]:
a.dtype

dtype('int16')

In [25]:
#get size
a.itemsize

4

In [30]:
#get size means the total number of elements
a.size

5

In [31]:
#get total size; this gives the total bytes
a.nbytes

20

### Accessing/Changing specific elements,rows,columns,etc

In [34]:
a = np.array([[1,2,3,4,5,6,7],[8,7,6,5,4,3,2]])
print(a)

[[1 2 3 4 5 6 7]
 [8 7 6 5 4 3 2]]


In [35]:
#Get a specific element [r,c]; here the slicing r is the selection of rows 
# the c selects the index of the element in the list/array 
a[1,2] #6

6

In [36]:
# get a specific row; the entire row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [37]:
#get a specific column
a[:,2]

array([3, 6])

In [38]:
# getting a little more fancy [startindex:stopindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [39]:
# change a specific number from the row and column [r,c]
a[1,5] =20

In [41]:
#change the numbers from the columns
a[:,2] = 0

In [42]:
a

array([[ 1,  2,  0,  4,  5,  6,  7],
       [ 8,  7,  0,  5,  4, 20,  2]])

#### *3-D example

In [43]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [44]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [45]:
b.shape

(2, 2, 2)

In [46]:
#get a specific element (work outside in)
b[0,1,1]

4

In [ ]:
#play around
b[:,0,:]
#here this means that i) we want to consider both the rows
#ii) here we want to consider the first index rows of both the outer rows
#iii) here we consider both the elements

In [49]:
# replace values in the array
b[:,1,:] = [[9,9],[8,8]]
#here it is necesary to get the change in the same dimension as the one
#it is already in


In [50]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializeing different types of Arrays

In [62]:
# All 0s matrix; here we realise that for a 1D+ we need double parenthesis(())
np.zeros((1))

array([0.])

In [63]:
# All 1s matrix
np.ones((4,4),dtype='int32')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [66]:
#any other number; here we have only 1 input number;also include dtype if
#you want to have small size because of small numbers
np.full((2,2),3,dtype='int16')

array([[3, 3],
       [3, 3]], dtype=int16)

In [ ]:
#any other number (full_like); allows us to take a shape that is already built
np.full_like(a,5)

In [69]:
#same as above but different syntax
np.full(a.shape,55)

array([[55, 55, 55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55, 55, 55]])

In [71]:
#random decimal numbers
np.random.rand(4,2)

array([[0.5239287 , 0.07184121],
       [0.48195993, 0.10918342],
       [0.3561414 , 0.43197859],
       [0.7046181 , 0.21274334]])

In [72]:
#using an existing dimension for random decimal
np.random.random_sample(a.shape)

array([[0.00881879, 0.86386477, 0.67120462, 0.15161346, 0.39326535,
        0.1374334 , 0.73885967],
       [0.38733582, 0.79202314, 0.62174655, 0.92895464, 0.48458982,
        0.17698375, 0.61127101]])

In [84]:
#random integer values
np.random.randint(-11,8,size=(3,3))

array([[ 2,  1,  7],
       [-1, -7, -6],
       [-6,  0, -9]])

In [85]:
#get an identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [87]:
#here we use numpy to repeat an array
# we made an array of 3 elements now np.repeat has a syntax(array,repeats)
#this repeats the element as shown below
arr = np.array([1,2,3]) #the array here is a vector
r1 = np.repeat(arr,3)
r1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [88]:
#here we get the array one below the other by using axis=0
arr = np.array([[1,2,3]]) #adding 2 square brackets makes it a 2D array
r1 = np.repeat(arr,3,axis=0) #inputting 1 in axis will give the above results
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [97]:
## how to initialize an array
b = np.ones((5,5),dtype='int16')
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [98]:
#think before doing the work, we could manually chnage the elements 
#but using a zeroes and then inputting the term in the middle was an easier betb[1:4,1:4] = np.zeros((3,3))

In [103]:
b[2,2] = 9

In [104]:
b

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

#### Be careful when copying arrays

In [127]:
a = np.array([1,2,3])
b = a.copy()
c = a
a


array([1, 2, 3])

In [128]:
b[0] = 10
c[1] = 20
print(a)
print(b)
print(c)
#here we see that both a and b have 10 in the array instead of just the b 
#element so avoid this problem we should .copy() the new variable

# here we see that wen we use the .copy the elements are just copied and the
#new assignment in b doesn't affect the a but the c assignment does

[ 1 20  3]
[10  2  3]
[ 1 20  3]


## Mathematics

In [ ]:
#it helps in arithmatics addition,subs div and multiply

In [129]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [130]:
#addition
a+2

array([3, 4, 5, 6])

In [131]:
#subtraction
a-2

array([-1,  0,  1,  2])

In [132]:
#multiply
a*2

array([2, 4, 6, 8])

In [133]:
#division
a/2 #returns float

array([0.5, 1. , 1.5, 2. ])

In [134]:
b = np.array([1,0,1,0])

In [135]:
a+b

array([2, 2, 4, 4])

In [136]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [138]:
# take the sine of all the values
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

### Linear Algebra

In [150]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [151]:
# the .full helps me create a matrix of required shape and value
b = np.full((3,2),2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [168]:
#to performa matrix multiplication use .matmul(2arguments)
d = np.matmul(a,b)
d[1,1] = 8

In [169]:
d

array([[6., 6.],
       [6., 8.]])

In [170]:
# finding the determinant
np.linalg.det(d)

12.0

In [ ]:
#http://docs.scipy.org/doc/numpy/reference/routines.linalg.html
#reference docs
#Determinant
#Trace
#singular vector decomposition
#matrix norm
#inverse


### Statistics

In [171]:
stats = np.array([[1,2,3],[4,5,6]])

In [172]:
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [180]:
#to find the min in array
#using the axis we will get all the min in rows for axis=1 and all the min
#column values for axis=0
print(np.min(stats))
np.min(stats,axis=0)

1


array([1, 2, 3])

In [174]:
#to find max
#same goes for the max using axis
np.max(stats)

6

In [185]:
#to sum all the values in the array we can do it using the np.sum()
#with axis = 0 sums the columns and with axis = 1 sums the rows
np.sum(stats)

21

### Reorganizing Array

In [186]:
before = np.array([[1,2,3,4],[5,6,7,8]])

In [191]:
print(before)

#here we are reshaping the array based on the given shape in parenthesis
# also reshaping is possible based on the number of elements so the 
#multiplication of the element should be the multiplication of the shape
after = before.reshape((1,8))
after

[[1 2 3 4]
 [5 6 7 8]]


array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [193]:
# vertically stacking vectors
#this stacks the vectors one top of the other
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack((v1,v2,v2,v2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [197]:
#horizontal stacks
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

#to get the h1 behind h2
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous

#### Load Data from file

In [198]:
#how to load data from the txt file
#--np.genfromtxt('data.txt',delimiter=',')
#using the .astype('int__') we can convert the array to an interger from float
#--filname = np.genfromtxt('data.txt',delimiter=',').astype('int__')

##### Boolean Masking and Advanced Indexing

In [199]:
#check where in file data the value is greater than 50
#--filename > 50
#any logical operator
#here we can get the elements also by inputting the logical oeprator
#and that will return the values in the array
#--filename[filename>50]



In [200]:
## you can index with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [ ]:
#to check in columns whether the values are greater than 50 using axis=
#this give an OR statement(.any()) for all vlaues in column (.all())
#--np.any(filename> 50, axis=0)

In [ ]:
#multiple statements
#--((filename>50) & (filename<100))
#--(~((filename>50)&(filename<100)))

In [203]:
np.array([[1,2,3,4,5],[6,7,8,9,10]])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [214]:
a = np.genfromtxt('1.txt',delimiter=',')

In [213]:
#to select item from a matrix and return a matrix for the same
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [215]:
a[2:4,0:2]

array([[11., 12.],
       [16., 17.]])

In [216]:
#to get diagnal from the matrix
a[[0,1,2,3],[1,2,3,4]]

array([ 2.,  8., 14., 20.])

In [220]:
#when using numpy to select specific rows we use [] brackets, but when slicing
# no square brackets are needed for the columns
a[[0,4,5],3:]

array([[ 4.,  5.],
       [24., 25.],
       [29., 30.]])