### 1. Import NumPy as np and see version

In [1]:
import numpy as np
np.version.version

'1.18.5'

### 2. How to create a 1D array?

In [28]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 3. How to create a boolean array?

In [10]:
boolean_arr = np.ones((3,3),dtype=bool)
boolean_arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### 4. How to extract items that satisfy a given condition from 1D array?

In [11]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.where(arr%2)

(array([1, 3, 5, 7, 9], dtype=int64),)

### OR

In [20]:
arr[arr % 2 ==1]

array([1, 3, 5, 7, 9])

### 5. How to replace items that satisfy a condition with another value in numpy array?

In [23]:
np.where(arr%2!=1,arr,-1)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### OR

In [25]:
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### 6. How to replace items that satisfy a condition without affecting the orignal array?

In [26]:
np.where(arr%2!=1,arr,-1)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [29]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 7. How to reshape an array?

In [30]:
arr = np.arange(10)

In [31]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
arr.reshape(2,-1) # .reshape(rows,columns) using -1 we can have an unknown

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 8. How to stack two arrays vertically?

In [42]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)

In [43]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [44]:
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [51]:
# Method 1
np.concatenate([a,b],axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [52]:
# Method 2
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [53]:
# Method 3
np.c_[a,b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

### 10. How to generate custom sequences in numpy without hardcoding?

In [54]:
a = np.array([1,2,3])

In [57]:
np.concatenate((np.repeat(a,3),a,a,a))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [58]:
# this is a numpy function which repeats the series of the array
np.tile(a,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [60]:
# this is the nupy function used to concatenate along axis 1
#  np.r_()

### 11. How to get the common items between two python numpy arrays?

In [61]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [62]:
np.intersect1d(a,b)

array([2, 4])

### 12. How to remove from one array those items that exist in another?

In [64]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [65]:
np.setdiff1d(a,b)

array([1, 2, 3, 4])

### 13. How to get the positions where elements of two arrays match?

In [66]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [67]:
# .where gives us the index in the array
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

### 14. How extract all numbers between a given range from a numpy array?

In [75]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [78]:
# Method 1

# .where gives us the index in the array
# hence
a[np.where((a>5) & (a<=10))]

array([ 6,  9, 10])

In [79]:
# Method 2

a[(a>=5) & (a<=10)]

array([ 6,  9, 10])

### 15. How to make a python function that handles scalars to work on numpy arrays?

In [94]:
# to solve the above question first we need to create a max function which 
# evaluates which of the two numbers is max
def maxx(a,b):
        if a >= b:
            return a
        else:
            return b

In [98]:
#Takes in a multiple sequence of numpy inputs and returns single numpy array
pair_max = np.vectorize(maxx, otypes=[float])

In [102]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

In [103]:
pair_max(a,b)

array([6., 7., 9., 8., 9., 7., 5.])

### 16. How to swap two columns in a 2d numpy array?

In [105]:
arr = np.arange(9).reshape(3,-1)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [107]:
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

### 17. How to swap two rows in a 2d numpy array?

In [108]:
arr = np.arange(9).reshape(-1,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [109]:
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

### 18. How to reverse the columns on a 2D array?

In [110]:
arr = np.arange(9).reshape(-1,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [114]:
# Method 1
np.flip(arr,axis=1)

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [116]:
# Method 2
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

### 19. How to reverse the rows on a 2D array?

In [118]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [119]:
arr[::-1,:]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [120]:
np.flip(arr,axis=0)

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

### 20. How to create a 2D array containing random floats between 5 and 10?

In [139]:
import random

arr = np.array(np.random.randint(5,10,15)).reshape(5,3) + np.random.random((5,3))

In [140]:
arr

array([[9.20413626, 6.40514955, 8.74155819],
       [9.26142862, 9.45475029, 6.24371615],
       [5.64247241, 6.15282114, 8.28985517],
       [9.09918472, 8.49164265, 9.99815003],
       [5.217659  , 8.2617201 , 6.18876225]])

In [136]:
np.array(np.random.random((5,3)))

array([[0.71645722, 0.43193135, 0.59945628],
       [0.45793793, 0.45509062, 0.93527866],
       [0.35391969, 0.35782936, 0.59162384],
       [0.52713413, 0.26708456, 0.22093073],
       [0.42579673, 0.78106902, 0.20178283]])